# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='projectname',
        ),
    ]
